version: '3.2'
services:
  springbootapp:
    image: pradeeppant/bootcamp-hands-1:1.0.0
    ports:
      - '8888:8080'
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - "mysql_data:/var/lib/mysql"

volumes:
  mysql_data: